name: Validate HomePrep

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "23 4 * * 1"

permissions:
  contents: read

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration

  hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
